# Generated by Django 2.0.7 on 2018-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='user',
            field=models.CharField(max_length=150, verbose_name='用户'),
        ),
    ]
